version: '3'
services:
  bws:
    image: node:latest
    container_name: "bws"
    volumes:
      - .:/app/bws
    working_dir: /app/bws
    ports:
      - ${PORT:-3232}:3232
    command: "npm run app"
    environment: 
      - MONGO_URL=${MONGO_URL:-mongodb://218.168.168.150:27017}